version: "{build}-{branch}"

init:
  - git config --global core.autocrlf true

environment:
  PYTHONIOENCODING: "utf-8"
  matrix:
    - PYTHON: "C:/Python36-x64"

install:
  - cmd: "%PIP% install Django"
  - cmd: cd src/main/python && %PYTHON%\python test.py
#  - cmd: cd bookShop && %PYTHON%\python manage.py makemigrations && %PYTHON%\python manage.py migrate


build: off

test_script:
  - "%PYTHON%\\python.exe test.py"

notifications:
  - provider: Email
    to:
      - chenfh5@qq.com
    on_build_status_changed: true